# Site settings
title: A Survey on Visual Analytics for 3D Urban Data
description: "Website for Urban Survey"
baseurl: "/vis"
url: "https://urban-survey.github.io/"
domain: "urban-survey.github.io"
github_username: urban-survey/vis

youtube_username:
facebook_page:
safe: false
lsi: false
google_analytics: "'--'"
use_analytics: false

plugins:
  - jekyll-redirect-from
  # - jekyll/scholar

# Build settings
permalink: pretty
sass:
  sass_dir: _sass
# exclude from build
exclude: ["README.md", ".idea/"]

# Collections
collections:
  # persons:
  #   output: true
  # videos:
  #   output: false
  # institutions:
  #   output: false
  # projects:
  #   output: true
  techniques:
    output: true
    permalink: /techniques/:path/
